#!/usr/bin/env Rscript

library(limma)
library(data.table)

main <- function() {

     #fstdata =as.data.frame(fread("../../manhat/manhatify_test/testout_manhat_format.txt", header=TRUE))
     #fstdata = fstdata[!is.nan(fstdata$P),]
     #xtxdata =as.data.frame(fread("/home/jgbaldwinbrown/Documents/work_stuff/clam_shrimp/shrimp_assembly/assembly_paper/paper/word_version/fst_version_52_gbe_revision/new_stuff/full_baypass/Baldwin-Brown_2017_Scripts/revision_scripts/manhat/subsets/manhatify_test/xtxsorted.txt", header=TRUE))
     #xtxdata = xtxdata[!is.nan(xtxdata$P),]
     #bextxdata =as.data.frame(fread("../../manhat/bayenv_xtx/out_manhat_format.txt", header=TRUE))
     #bextxdata = bextxdata[!is.nan(bextxdata$P),]
     #oldfstdata = as.data.frame(fread("/home/jgbaldwinbrown/Documents/work_stuff/clam_shrimp/shrimp_assembly/assembly_paper/paper/word_version/fst_version_52_gbe_revision/new_stuff/full_baypass/Baldwin-Brown_2017_Scripts/revision_scripts/manhat/old_correct_fst/out_manhat_format_nonan.txt", header=TRUE))
     #oldfstdata = oldfstdata[!is.nan(oldfstdata$P),]
     #fstdata$BP2 = fstdata$BP-1
     #oldfstdata$BP2 = oldfstdata$BP-1
     #bextxdata$BP2 = bextxdata$BP-1
     #xtxdata$BP2 = xtxdata$BP-1
     #bigdata = merge(fstdata, xtxdata, by = c("CHR", "BP2", "BP"), sort=TRUE, all=TRUE)
     #bigdata = merge(bigdata, bextxdata, by = c("CHR", "BP2", "BP"), sort=TRUE, all=TRUE)
     #bigdata = merge(bigdata, oldfstdata, by = c("CHR", "BP2", "BP"), sort=TRUE, all=TRUE)
     #bigdata2 = bigdata[complete.cases(bigdata),]
     #colnames(bigdata) = c("CHR", "BP2", "BP", "SNP_FST", "FST", "SNP_XTX", "XTX", "SNP_BEXTX", "BEXTX", "SNP_OLDFST", "OLDFST")
     #colnames(bigdata2) = c("CHR", "BP2", "BP", "SNP_FST", "FST", "SNP_XTX", "XTX", "SNP_BEXTX", "BEXTX", "SNP_OLDFST", "OLDFST")
     #bigdata2_sig = bigdata2[
     #    (bigdata2$FST > 0.7 & !is.na(bigdata2$FST)) |
     #    (bigdata2$XTX > 30 & !is.na(bigdata2$XTX)) |
     #    (bigdata2$BEXTX > 40 & !is.na(bigdata2$BEXTX)) |
     #    (bigdata2$OLDFST > 0.8 & !is.na(bigdata2$OLDFST))
     #    ,
     #]
     #bigdata2_sigbed = bigdata2_sig[,1:3]
     #rm(bigdata)
     #rm(bigdata2)
     #rm(xtxdata)
     #rm(fstdata)
     #rm(oldfstdata)
     #rm(bextxdata)
     #gc()
     #write.table(bigdata2_sigbed, "bigdata2_sigbed.txt")
    
    
    old_data = as.data.frame(fread("/home/jgbaldwinbrown/Documents/work_stuff/clam_shrimp/shrimp_assembly/assembly_paper/paper/word_version/fst_version_52_gbe_revision/new_stuff/full_baypass/Baldwin-Brown_2017_Scripts/revision_scripts/full_run/data/snpbeds/all_beds/old_correct/uncens_bedified_snpsfile_correct.bed"))
    print(1)
    hc200_data = as.data.frame(fread("/home/jgbaldwinbrown/Documents/work_stuff/clam_shrimp/shrimp_assembly/assembly_paper/paper/word_version/fst_version_52_gbe_revision/new_stuff/full_baypass/Baldwin-Brown_2017_Scripts/revision_scripts/full_run/data/snpbeds/all_beds/haplocaller_200ploid/degs.input.bedified.bed.count"))
    print(2)
    sam_data = as.data.frame(fread("samint.bed.count"))
    print(3)
    hc2_data = as.data.frame(fread("/home/jgbaldwinbrown/Documents/work_stuff/clam_shrimp/shrimp_assembly/assembly_paper/paper/word_version/fst_version_52_gbe_revision/new_stuff/full_baypass/Baldwin-Brown_2017_Scripts/revision_scripts/full_run/data/snpbeds/all_beds/haplocaller_2ploid/degs.input.bedified.bed.count"))
    print(4)
    colnames(old_data[1:3]) = c("CHR", "BE2", "BE")
    print(5)
    old_data_sig = merge(bigdata2_sigbed, old_data)
    print(6)
    rm(old_data)
    print(7)
    m_old_data = melt(old_data_sig, id.vars=c("V1", "V2", "V3"))
    print(8)
    rm(old_data_sig)
    print(9)
    gc()
    print(10)
    colnames(hc200_data[1:3]) = c("CHR", "BE2", "BE")
    print(11)
    hc200_data_sig = merge(bigdata2_sigbed, hc200_data)
    print(12)
    rm(hc200_data)
    print(13)
    m_hc200_data = melt(hc200_data_sig, id.vars=c("V1", "V2", "V3"))
    print(14)
    rm(hc200_data_sig)
    print(15)
    gc()
    print(16)
    colnames(hc2_data[1:3]) = c("CHR", "BE2", "BE")
    print(17)
    hc2_data_sig = merge(bigdata2_sigbed, hc2_data)
    print(18)
    rm(hc2_data)
    print(19)
    m_hc2_data = melt(hc2_data_sig, id.vars=c("V1", "V2", "V3"))
    print(20)
    rm(hc2_data_sig)
    print(21)
    gc()
    print(22)
    print("pre-melt sam")
    print(23)
    colnames(sam_data[1:3]) = c("CHR", "BE2", "BE")
    print(24)
    sam_data_sig = merge(bigdata2_sigbed, sam_data)
    print(25)
    rm(sam_data)
    print(26)
    m_sam_data = melt(sam_data_sig, id.vars=c("V1", "V2", "V3"))
    print(27)
    print("melted sam")
    print(28)
    rm(sam_data_sig)
    print(29)
    gc()
    print(30)
    print("pre-merge")
    print(31)
    bigdata = merge(m_old_data, m_hc200_data, by=c("V1", "V2", "V3", "variable"))
    print(32)
    print("merging 1")
    print(33)
    rm(m_old_data, m_hc200_data)
    print(34)
    gc()
    print(35)
    bigdata = merge(bigdata, m_sam_data, by=c("V1", "V2", "V3", "variable"))
    print(36)
    print("merging 2")
    print(37)
    rm(m_sam_data)
    print(38)
    gc()
    print(39)
    bigdata = merge(bigdata, m_hc2_data, by=c("V1", "V2", "V3", "variable"))
    print(40)
    print("merging 3")
    print(41)
    rm(m_hc2_data)
    print(42)
    gc()
    print(43)
    write.table(bigdata, "bigdata_af_sig.txt", quote=FALSE, sep="\t")
    print(44)
    bigdata = bigdata[complete.cases(bigdata),]
    print(45)
    colnames(bigdata) = c("CHR", "BP", "BP2", "COL", "UG", "HC200", "SAM", "HC2")
    print(46)
    write.table(bigdata, "bigdata2_af_sig.txt", quote=FALSE, sep="\t")
    print(47)
    bigdata_mini = bigdata[,c("UG", "HC200", "SAM", "HC2")]
    print(48)
    corr_mini = cor(bigdata_mini)
    print(49)
    write.table(corr_mini, "corr_mini_af_sig.txt", quote=FALSE, sep="\t")
    print(50)
    corr = cor(bigdata)
    print(51)
    write.table(corr, "corr_af_sig.txt", quote=FALSE, sep="\t")
    print(52)
}

main()

